export const NEW_PROJECT_FETCH_APP_TYPES_BEGIN = 'NEW_PROJECT_FETCH_APP_TYPES_BEGIN';
export const NEW_PROJECT_FETCH_APP_TYPES_SUCCESS = 'NEW_PROJECT_FETCH_APP_TYPES_SUCCESS';
export const NEW_PROJECT_FETCH_APP_TYPES_FAILURE = 'NEW_PROJECT_FETCH_APP_TYPES_FAILURE';
export const NEW_PROJECT_FETCH_APP_TYPES_DISMISS_ERROR = 'NEW_PROJECT_FETCH_APP_TYPES_DISMISS_ERROR';
export const NEW_PROJECT_CREATE_APP_BEGIN = 'NEW_PROJECT_CREATE_APP_BEGIN';
export const NEW_PROJECT_CREATE_APP_SUCCESS = 'NEW_PROJECT_CREATE_APP_SUCCESS';
export const NEW_PROJECT_CREATE_APP_FAILURE = 'NEW_PROJECT_CREATE_APP_FAILURE';
export const NEW_PROJECT_CREATE_APP_DISMISS_ERROR = 'NEW_PROJECT_CREATE_APP_DISMISS_ERROR';
